# Generated by Django 5.2.3 on 2025-07-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriageproposals',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Approved'), (0, 'Canceled'), (-1, 'In waiting...')], default=-1, verbose_name='status'),
        ),
    ]
