# Generated by Django 5.2.3 on 2025-07-29 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriage',
            name='husband',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='husband', to=settings.AUTH_USER_MODEL, verbose_name='Муж'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Активный'), (0, 'Расторгнут')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='wife',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wife', to=settings.AUTH_USER_MODEL, verbose_name='Жена'),
        ),
    ]
