# Generated by Django 5.2.3 on 2025-07-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_marriageproposals_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marriageproposals',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='marriageproposals',
            name='receiver_fullname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unregistered user'),
        ),
        migrations.AlterUniqueTogether(
            name='marriageproposals',
            unique_together={('sender', 'receiver', 'status'), ('sender', 'receiver_fullname', 'status')},
        ),
    ]
