# Generated by Django 5.2.3 on 2025-07-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_marriageproposals_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marriageproposals',
            unique_together=set(),
        ),
    ]
