# Generated by Django 5.2.3 on 2025-07-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_photo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marriage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='marriage',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Divorced')], default=1, verbose_name='status'),
        ),
        migrations.AlterUniqueTogether(
            name='marriage',
            unique_together={('husband', 'wife', 'status')},
        ),
    ]
