# Generated by Django 5.2.3 on 2025-07-24 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_marriage_unique_together_marriage_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriage',
            name='husband',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='husband', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='wife',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wife', to=settings.AUTH_USER_MODEL),
        ),
    ]
