# Generated by Django 5.2.3 on 2025-07-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_marriage_husband_alter_marriage_wife'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marriage',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='marriage',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('husband', 'wife', 'status'), name='unique_active_marriage'),
        ),
    ]
