# Generated by Django 5.2.3 on 2025-07-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_marriage_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Man'), (0, 'Woman')], default=None),
        ),
    ]
