# Generated by Django 5.2.3 on 2025-07-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marriage',
            name='unique_active_marriage',
        ),
        migrations.AddConstraint(
            model_name='marriage',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('husband', 'status'), name='unique_active_husband'),
        ),
        migrations.AddConstraint(
            model_name='marriage',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('wife', 'status'), name='unique_active_wife'),
        ),
    ]
